### ISSUE TITLE
Dodawanie i edycja, klonowanie

### ISSUE THREAD

**Issue by tomekk44** [Jarczyslaw/Barcodes#3]
Fajnie jakby przy dodawaniu była czysta formatka.
Edycja zawsze wyświetlała dane edytowanego kodu.
I była opcja sklonuj, gdzie powstaje nowy kod i otwiera się okno dodawania z uzupełnionymi danymi i fokus na numerze UNIQ

**Comment by Jarczyslaw** [comment]
W wersji 1.2 poprawiono dziwne zachowanie formatek do generowania kodów. Teraz formatki czyszczą się kiedy trzeba oraz istnieje możliwość edycji danych (jeśli pasują np. do EAN128). Opcja klonowania jest możliwa poprzez edycję kodu oraz użycia przycisku "Add new".
